spring:
  application:
    name: practice
  datasource:
    url: jdbc:mysql://localhost:3306/practice?useSSL=false&allowPublicKeyRetrieval=true
    username: caoboiloi
    password: huynhtanloi
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8888