spring:
  application:
    name: practice
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8888

# Custom Application Configuration
custom:
  datasource:
    url: jdbc:mysql://localhost:3306/practice?useSSL=false&allowPublicKeyRetrieval=true
    username: caoboiloi
    password: huynhtanloi
    driver-class-name: com.mysql.cj.jdbc.Driver
  database:
    connection-timeout: 30000
    maximum-pool-size: 10
    minimum-idle: 5
  
  security:
    jwt:
      secret: mySecretKey
      expiration: 86400000 # 24 hours
    cors:
      allowed-origins:
        - http://localhost:3000
        - http://localhost:4200
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
  
  features:
    enable-logging: true
  
  pagination:
    default-page-size: 6
    max-page-size: 100